version: 1.0.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}'
build:
  project: seq-app-digestemail.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: owIruqEXZlFwqcSBYyjR19/8EodS+aXFzZmBwqlaYnDE/uy1X+KsuI5QH3p9iBmx
  on:
    branch: master
    